# render.yaml
services:
  - type: web
    name: cofre-campneus
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PGHOST
        value: ep-crimson-meadow-a8krhs13.eastus2.azure.neon.tech
      - key: PGDATABASE
        value: senhas_campneus
      - key: PGUSER
        value: senhas_campneus_owner
      - key: PGPASSWORD
        value: npg_MXP5UK4CqToH
      - key: PGSSLMODE
        value: require
      - key: PGCHANNELBINDING
        value: require
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: cofre-campneus-secret-key-change-in-production
    healthCheckPath: /login