# render.yaml
services:
  - type: web
    name: cofre-campneus
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: cofre-campneus
          envVarKey: PORT
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_HTTP_ONLY
        value: true
      - key: COOKIE_MAX_AGE
        value: 86400000
      - key: DB_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: postgres-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: postgres-db
          property: port

databases:
  - name: postgres-db
    plan: standard
    ipAllowList: []